[package]
name = "hitster_core"
version = "0.1.0"
edition = "2024"

[dependencies]
multi_key_map = { workspace = true }
natord = "1.0.9"
serde = { workspace = true }
time = { workspace = true }
uuid = { workspace = true }
