on:
  push:
    branches:
      - main
      - development
    tags:
      - '**'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Dump job github var
        env:
          GITHUB_VAR: ${{ toJson(github) }}
        run: echo "$GITHUB_VAR"
      - 
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: "Log in to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push Docker dev image
        if: startsWith(github.ref, 'refs/heads/development')
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: tonironaldbarth/hitster:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - 
        name: Build and push Docker stable image
        if: startsWith(github.ref, 'refs/tags') && !github.event_type != 'pull_request'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: tonironaldbarth/hitster:latest , tonironaldbarth/hitster:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
